# Generated by Django 3.2.8 on 2021-10-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211019_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='latitude',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='longitude',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
    ]
