# Generated by Django 3.2.8 on 2021-10-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211019_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_ip',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='type_ip',
        ),
    ]
